name: TMDiscordBot
version: 3.0.0
main: com.github.hoshikurama.tmdiscord.BukkitPlatform
api-version: 1.18
authors: [HoshiKurama]
depend: [TicketManager]
commands:
  tmdiscord:
    description: Access to reload
    permission: tmdiscord.reload
permissions:
  tmdiscord.reload:
    description: Allows /tmdiscord reload
    default: op